### ISSUE TITLE
Get cURL cerificate errors

### ISSUE THREAD

**Issue by intothevoid** [ivkos/PushBullet-for-PHP#23]
Thank you for this wrapper around the PushBullet API. Its very useful. I receive the following error when I use the class and use a method like getUserInformation() or getDevices() -

Error: cURL Error: SSL certificate problem: self signed certificate in certificate chain

Soln: Adding the following line to PushBullet.class.php fixes the problem for me -
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

I'm new to Git I don't know how to submit a pull request. I'll give it a shot anyways. Cheers!

**Comment by fabmsg** [comment]
hi! i'm having the same problem, but I'm running my server on Linux... what should i do? 
thanks!

**Comment by ivkos** [comment]
```php
Pushbullet\Connection::setCurlCallback(function ($curl) {
    // Get a CA certificate bundle here:
    // https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
    curl_setopt($curl, CURLOPT_CAINFO, 'C:/path/to/ca-bundle.crt');

    // Not recommended! Makes communication vulnerable to MITM attacks:
    // curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
});

```

**Comment by fabmsg** [comment]
Sorry I'm new to this...
But in the file "PushBullet.class.php" where should I put that code? in the end?
thanks!

**Comment by ivkos** [comment]
You don't need to edit the library's files. Also, I think you're using a version that is too old and unsupported. Please download the latest version via Composer. If you are new to it, have a look here:

https://getcomposer.org/download/
https://getcomposer.org/doc/00-intro.md

After that you can follow the README here:
https://github.com/ivkos/Pushbullet-for-PHP/blob/master/README.md
