### ISSUE TITLE
Push on a pushbullet channel ? 

### ISSUE THREAD

**Issue by ImChip** [ivkos/PushBullet-for-PHP#31]
how to push a news on a pushbullet own channel 

https://www.pushbullet.com/channels

**Comment by ivkos** [comment]
First, you need to create your own channel: https://www.pushbullet.com/my-channel

Then, you can push links to it like so:
```php
$pb = new PushBullet('API_KEY');

$pb->pushLink(
   '#mychannelname', // note the # sign
   'News Title',
   'https://example.com/news/2015/01/news-link',
   'News body in summary...'
);
```

Let me know if you have any problems sending push notifications to a channel this way.

**Comment by ImChip** [comment]
Ty for this fast respond guys ! :) 

i try now

**Comment by ImChip** [comment]
its work ty man !

**Comment by scuba323** [comment]
I get;  
HTTP Error 400 (invalid_request): The param 'channel_tag' has an invalid value.

**Comment by Pe46dro** [comment]
I tried 
```php
$pb->pushFile(
	"#mychannelname",
	"address",
	"mime",
	"title",
	"desc",
	"name.jpg"
);
```
But it don't work, can i push file to a channel?

**Comment by ivkos** [comment]
You can push files to channels.

Are you getting any error messages? Do you own the channel you're trying to push to?

**Comment by Pe46dro** [comment]
PHP Fatal error:  Call to undefined method Pushbullet\\Pushbullet::pushFile() in /dir/index.php on line 25

```php
$pb->pushFile(
		"#channel",
	    "photo",
	    "mime",
	    "title",
	    "desc",
	    "name"
	);
```

**Comment by ivkos** [comment]
I think you're trying to use v2 code on v3.

On v3 you can push to channels like so:
```php
$pb = new Pushbullet\Pushbullet('YOUR_ACCESS_TOKEN');

$pb->channel("mychannel")->pushFile(
    "/home/ivkos/photos/20150314_092653.jpg",
    "image/jpeg",
    "Look at this photo!",
    "I think it's pretty cool",
    "coolphoto.jpg"
);
```


Also, you can read the readme for more information:
https://github.com/ivkos/Pushbullet-for-PHP/blob/master/README.md

**Comment by Pe46dro** [comment]
I tried your code whit dev-master version and i got this error:
PHP Fatal error:  Uncaught exception 'Pushbullet\\Exceptions\\NotPushableException' with message 'Cannot push to this target.' in /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php:218
Stack trace:
-0 /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php(55): Pushbullet\\Channel->checkPushable()
-1 /dir/index.php(25): Pushbullet\\Channel->pushNote('Hello world!', 'Lorem ipsum...')
-2 {main}  thrown in /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php on line 218

**Comment by ivkos** [comment]
Are you the owner of the channel you're pushing to? Have you created it before pushing?

```php
$pb->channel("mychannel")->create("My Channel", "This channel will only push awesome stuff!");

$pb->channel("mychannel")->pushNote(...);
```

**Comment by Pe46dro** [comment]
I creat a channel from Pushbullet website, now i created one whit PHP... when i use
```php
$pb->getMyChannels()
```

i got this:
```text
array(3) {
  [0]=>
  object(Pushbullet\Channel)#3 (14) {
    ["channelTag":"Pushbullet\Channel":private]=>
    string(20) "tag"
    ["type":"Pushbullet\Channel":private]=>
    string(7) "channel"
    ["recipientType":"Pushbullet\Channel":private]=>
    string(11) "channel_tag"
    ["recipient":"Pushbullet\Channel":private]=>
    string(20) "tag"
    ["apiKey":protected]=>
    string(32) "11111111111111111111111111111111"
    ["active"]=>
    bool(true)
    ["iden"]=>
    string(22) "1111111111111111111111"
    ["created"]=>
    float(1429812437.1747)
    ["modified"]=>
    float(1429812437.1747)
    ["tag"]=>
    string(20) "tag"
    ["name"]=>
    string(22) "name"
    ["description"]=>
    string(61) "desc"
    ["myChannel"]=>
    bool(true)
    ["pushable"]=>
    bool(true)
  }
...
```
butt when i use:
```php
$pb->channel("channel")->pushNote("Hello world!", "Lorem ipsum...");
```

i got this from php:
```text
PHP Fatal error:  Uncaught exception 'Pushbullet\\Exceptions\\NotPushableException' with message 'Cannot push to this target.' in /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php:218
Stack trace:
#0 /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php(55): Pushbullet\\Channel->checkPushable()
#1 /dir/test.php(18): Pushbullet\\Channel->pushNote('Hello world!', 'Lorem ipsum...')
#2 {main} thrown in /dir/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php on line 218
```

Sorry but i really don't know why it don't work

**Comment by ivkos** [comment]
If you can't push to a channel this most likely means you are not its owner. Make sure you are pushing to the **same** channel tag you used to create the channel.

```php
$pb->channel("channel_tag_goes_here")->create("title", "description");
$pb->channel("channel_tag_goes_here")->pushNote("...", "...");
```

The code you have posted is inconsistent so I can't help you much unless I see what statements you're using to create a channel and then push to it.
