### ISSUE TITLE
Possible to send SMS by API ?

### ISSUE THREAD

**Issue by fturk** [ivkos/PushBullet-for-PHP#38]

**Comment by ivkos** [comment]
Yes, the Pushbullet API allows sending SMS texts. This feature however is not documented in the official API reference.

I've found a way to send SMS messages and implemented it in the `sendSms()` method in this library. Have a look at it here:
https://github.com/ivkos/PushBullet-for-PHP/blob/master/src/Pushbullet.php#L438

As far as I know, only Android is supported.

Let me know if you have any troubles using this functionality.
