### ISSUE TITLE
Possible to get Phone Contact of Gmail Contact ?

### ISSUE THREAD

**Issue by fturk** [ivkos/PushBullet-for-PHP#41]

**Comment by ivkos** [comment]
I don't think this is possible. Whatever the Pushbullet API returns on the contacts endpoint, that's the information you can get for a contact.

**Comment by ivkos** [comment]
The closest thing you can do is get a list of all entries in a device's phonebook by using `getPhonebook($device_iden)`. 

It's a new method I've just implemented. You can read its documentation here: https://github.com/ivkos/PushBullet-for-PHP/commit/5a54db49b6a3fcb1191dd593031e796a3a65511f

**Comment by fturk** [comment]
Thanks @ivkos :D !!
