### ISSUE TITLE
Uncaught exception when pushing to channel

### ISSUE THREAD

**Issue by maximelouet** [ivkos/Pushbullet-for-PHP#46]
Hi,
I'm trying to push a note to my channel, but I get a NotPushableException ('Cannot push to this target').
The code is really simple:

    $pb = new Pushbullet\Pushbullet("...");
    $pb->channel("my_channel")->pushNote("title","body");

The channel belongs to me, my python scripts are able to push to this channel with the same access token.

Can you tell me if I did something wrong, or if it's a bug? Thank you!

**Comment by ivkos** [comment]
Are you subscribed to your own channel?

**Comment by maximelouet** [comment]
Yes

**Comment by ivkos** [comment]
I think this might be a bug that occurs when you're subscribed to your own channel. Can you test if it works if you unsubscribe/unfollow your channel?

**Comment by maximelouet** [comment]
Well, I have unsubscribed from my channel, I don't get any error, but... I'd like to follow my own channel... I don't know what to do.
So yes it happens when you are subscribed to your own channel.

**Comment by maximelouet** [comment]
Thank you for the quick fix!! Great job!

**Comment by ivkos** [comment]
Thank you for your report!
