### ISSUE TITLE
How to delete pushes using v 3.*?

### ISSUE THREAD

**Issue by khurshid-alam** [ivkos/Pushbullet-for-PHP#47]
I noticed I can not delete pushes using version 3.1. When I try `$p->delete("$iden");` or `$p->deletePush("$iden");`, it complains about function not found. 

Is this feature supported in v 3.x.x?

**Comment by ivkos** [comment]
Deleting a push by giving its iden is not (yet) supported in v3. You can do something like:
```php
$pushes = $pb->getPushes();

for ($pushes as $push) {
   if ($push->iden == 'some_iden') {
      $push->delete();
      break;
   }
}
```

**Comment by khurshid-alam** [comment]
Thanks. That worked! But I think I will stay with v 2.x until this feature arrives in v 3.x.

**Comment by khurshid-alam** [comment]
@ivkos Any future plan to support this on 3.*?

**Comment by ivkos** [comment]
Yup. Since [v3.3.0](https://github.com/ivkos/Pushbullet-for-PHP/releases/tag/3.3.0) you can do it like so:

``` php
$pb = new Pushbullet(API_KEY);

$push = $pb->push("uZkYsjz6f28PhK4"); // finds the push with this iden

$push->delete();
```

**Comment by khurshid-alam** [comment]
Wow... Nice. Thanks.
