### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by developstar** [ivkos/Pushbullet-for-PHP#49]
Is sending lists not working anymore?

**Comment by developstar** [comment]
Fatal error: Uncaught exception 'Pushbullet\Exceptions\ConnectionException' with message 'HTTP Error 400 (invalid_request): The param 'type' has an invalid value.' in /mnt/webr/a0/65/54548565/htdocs/notification/vendor/ivkos/pushbullet/src/Pushbullet/Connection.php:106 Stack trace: #0 /mnt/webr/a0/65/54548565/htdocs/notification/vendor/ivkos/pushbullet/src/Pushbullet/Pushable.php(144): Pushbullet\Connection::sendCurlRequest('https://api.pus...', 'POST', Array, true, 'P63VqvG40bBfEa1...') #1 /mnt/webr/a0/65/54548565/htdocs/notification/spreeradio_kino.php(34): Pushbullet\Device->pushList('Shopping List', Array) #2 {main} thrown in /mnt/webr/a0/65/54548565/htdocs/notification/vendor/ivkos/pushbullet/src/Pushbullet/Connection.php on line 106

**Comment by ivkos** [comment]
Correct, pushing lists and addresses has been deprecated.

**Comment by developstar** [comment]
Is there an way to send lists with normal notes, so they have a line break between each item (like \n)?

**Comment by ivkos** [comment]
```php
$pb = new Pushbullet(YOUR_KEY);

$items = [
    "Bread",
    "Milk",
    "Cereal"
];

$pb->device("My Device")->pushNote("Items", join("\n", $items));
```
